# Generated by Django 5.2.5 on 2025-09-23 09:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'File Upload'), ('download', 'File Download'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('template_create', 'Template Create'), ('template_update', 'Template Update'), ('template_delete', 'Template Delete'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_delete', 'User Delete'), ('user_toggle_status', 'User Toggle Status'), ('api_key_generate', 'API Key Generate'), ('data_ingestion', 'Data Ingestion'), ('data_validation', 'Data Validation'), ('data_transformation', 'Data Transformation'), ('system_error', 'System Error')], max_length=50)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error'), ('warning', 'Warning')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='idx_audit_logs_user'), models.Index(fields=['username'], name='idx_audit_logs_username'), models.Index(fields=['action'], name='idx_audit_logs_action'), models.Index(fields=['status'], name='idx_audit_logs_status'), models.Index(fields=['timestamp'], name='idx_audit_logs_timestamp'), models.Index(fields=['resource'], name='idx_audit_logs_resource')],
            },
        ),
    ]
