# Generated by Django 5.2.5 on 2025-09-03 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('QUERY', 'Query Run'), ('EXPORT', 'Data Export')], max_length=10)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('roles', models.JSONField(default=list)),
                ('dataset', models.CharField(max_length=255)),
                ('columns', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('order_by', models.JSONField(default=list)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('offset', models.IntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('roles', models.JSONField(default=list)),
                ('dataset', models.CharField(max_length=255)),
                ('columns', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('order_by', models.JSONField(default=list)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(default='CSV', max_length=10)),
                ('signed_token', models.TextField(blank=True, null=True)),
                ('signed_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'export_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
