# Generated by Django 5.2.5 on 2025-08-21 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('file_name', models.TextField()),
                ('minio_key', models.TextField(unique=True)),
                ('bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded'), ('validated', 'validated'), ('failed', 'failed'), ('canceled', 'canceled')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'uploads',
                'indexes': [models.Index(fields=['user_id'], name='idx_uploads_user'), models.Index(fields=['status'], name='idx_uploads_status')],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_headers_missing', models.JSONField(default=list)),
                ('extra_headers', models.JSONField(default=list)),
                ('total_rows', models.BigIntegerField(blank=True, null=True)),
                ('empty_rows', models.BigIntegerField(blank=True, null=True)),
                ('encoding', models.CharField(blank=True, max_length=32, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='ingestion.upload')),
            ],
            options={
                'db_table': 'validation_reports',
            },
        ),
    ]
