# Generated by Django 5.2.5 on 2025-08-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='validationreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='upload',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='dataset',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='orchestrator_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='pipeline_run_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('validated', 'Validated'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='extra_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='required_headers_missing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['dataset'], name='idx_uploads_dataset'),
        ),
        migrations.AddIndex(
            model_name='upload',
            index=models.Index(fields=['created_at'], name='idx_uploads_created'),
        ),
    ]
