# Generated by Django 5.2.5 on 2025-09-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_add_template_models'),
        ('ingestion', '0002_alter_upload_options_alter_validationreport_options_and_more'),
    ]

    operations = [
    ]
