# Generated by Django 5.2.5 on 2025-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_merge_20250910_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('validated', 'Validated'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadextension',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
