# Generated by Django 5.2.5 on 2025-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_alter_upload_status_alter_uploadextension_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatemplate',
            name='target_table',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('transformed', 'Transformed'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
    ]
