# Dockerfile.django
FROM python:3.10-slim

# Install system deps (Postgres client for psycopg2, etc.)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python deps
COPY requirements.txt .
RUN pip install pandas
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

EXPOSE 8003

CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]
