---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: datawarehouse
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  CLICKHOUSE_USER: "user"
  CLICKHOUSE_PASSWORD: "password"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "default"
  TOKENIZATION_ENDPOINT: "http://tokenization-service:8004"
  TOKENIZATION_API_KEY: "your-secure-api-key-change-in-production"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: datawarehouse
data:
  DATABASE_URL: "postgresql://e2i_user:e2i_pass@orchestrator-postgres:5432/e2i_db"
  USE_LOCAL_WORKER: "false"
  AIRFLOW__BASE_URL: "http://airflow-webserver:8080"
  AIRFLOW__USERNAME: "airflow"
  AIRFLOW__PASSWORD: "airflow"
  DISABLE_HMAC: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: datawarehouse
data:
  DJANGO_DB_ENGINE: "django.db.backends.postgresql"
  DJANGO_DB_NAME: "e2i_db"
  DJANGO_DB_USER: "e2i_user"
  DJANGO_DB_PASSWORD: "e2i_pass"
  DJANGO_DB_HOST: "orchestrator-postgres"
  DJANGO_DB_PORT: "5432"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_BUCKET: "uploads"
  ORCHESTRATOR_URL: "http://orchestrator:8002/v1"
  DJANGO_DEBUG: "True"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: "default"
  CLICKHOUSE_USER: "user"
  CLICKHOUSE_PASSWORD: "password"
  REPORTING_EXPORT_DIR: "/app/exports"
  REPORTING_EXPORT_TTL: "3600"
  REPORTING_MAX_EXPORT_ROWS: "100000"
  DETOKENIZATION_ENDPOINT: "http://tokenization-service:8004"
  DETOKENIZATION_API_KEY: "your-secure-api-key-change-in-production"
  DETOKENIZATION_TIMEOUT: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tokenization-config
  namespace: datawarehouse
data:
  TOKENIZATION_API_KEY: "your-secure-api-key-change-in-production"
  TOKENIZATION_SALT: "your-secret-salt-change-in-production"
  TOKENIZATION_DB_URL: "postgresql://tokenization_user:tokenization_pass@tokenization-postgres:5432/tokenization_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: datawarehouse
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "metabase"
  MB_DB_PORT: "5432"
  MB_DB_USER: "metabase"
  MB_DB_PASS: "metabase"
  MB_DB_HOST: "metabase-postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: datawarehouse
data:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: datawarehouse
data:
  CLICKHOUSE_USER: "user"
  CLICKHOUSE_PASSWORD: "password"
  CLICKHOUSE_DB: "default"
